User.usuario_atual = User.find 1
Cargo.create(:codigo=>'2521-05',:nome=>'Administrador',:entidade_id=>'2')
Cargo.create(:codigo=>'2410-05',:nome=>'Advogado',:entidade_id=>'2')
Cargo.create(:codigo=>'4110-10',:nome=>'Assistente Administrativo',:entidade_id=>'2')
Cargo.create(:codigo=>'3224-15',:nome=>'Atendente de Consultório Dentário',:entidade_id=>'2')
Cargo.create(:codigo=>'3514-30',:nome=>'Auxiliar de Serviço Jurídico',:entidade_id=>'2')
Cargo.create(:codigo=>'4110-05',:nome=>'Auxiliar de Escritório em Geral',:entidade_id=>'2')
Cargo.create(:codigo=>'3181-05',:nome=>'Cadista',:entidade_id=>'2')
Cargo.create(:codigo=>'2522-10',:nome=>'Contador',:entidade_id=>'2')
Cargo.create(:codigo=>'5132-05',:nome=>'Cozinheiro Geral',:entidade_id=>'2')
Cargo.create(:codigo=>'4121-10',:nome=>'Digitador',:entidade_id=>'2')
Cargo.create(:codigo=>'2149-15',:nome=>'Engenheiro de Segurança do Trabalho',:entidade_id=>'2')
Cargo.create(:codigo=>'5143-20',:nome=>'Faxineiro',:entidade_id=>'2')
Cargo.create(:codigo=>'1425-15',:nome=>'Gerente de Produção de Tecnologia da Informação',:entidade_id=>'2')
Cargo.create(:codigo=>'1425-20',:nome=>'Gerente de Projeto de Tecnologia da Informação',:entidade_id=>'2')
Cargo.create(:codigo=>'5174-10',:nome=>'Porteiro de Edifícios',:entidade_id=>'2')
Cargo.create(:codigo=>'3171-10',:nome=>'Programador de Sistema de Informação',:entidade_id=>'2')
Cargo.create(:codigo=>'3132-20',:nome=>'Técnico em Manutenção de Equipamentos de Informática',:entidade_id=>'2')
Cargo.create(:codigo=>'3516-05',:nome=>'Técnico em Segurança no Trabalho',:entidade_id=>'2')
Cargo.create(:codigo=>'3222-15',:nome=>'Técnico de Enfermagem do Trabalho',:entidade_id=>'2')
Cargo.create(:codigo=>'3131-30',:nome=>'Técnico Eletricista',:entidade_id=>'2')
Cargo.create(:codigo=>'0000-01',:nome=>'Trabalhador de Serviço de Manutenção',:entidade_id=>'2')
