entidade||=Entidade.create(:nome=>"Governo do Estado do Amapá")
e = Entidade.find_by_nome("Governo do Estado do Amapá")
Orgao.create(:codigo=>'51',:nome=>'AG DE DEFESA INSPECAO AGROPECUARIA',:sigla=>'DIAGRO',:entidade_id=>e.id,:entidade_id=>e.id)
Orgao.create(:codigo=>'35',:nome=>'AGENCIA DE DESENVOLVIMENTO DO AMAPA',:sigla=>'ADAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'55',:nome=>'AGÊNCIA DE FOMENTO DO AMAPÁ',:sigla=>'AFAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'52',:nome=>'AGÊNCIA REG. DE SERV. PUB. DEL.-AP',:sigla=>'ARSAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'99',:nome=>'AMAPA PREVIDENCIA',:sigla=>'AMPREV',:entidade_id=>e.id)
Orgao.create(:codigo=>'13',:nome=>'AUDITORIA GERAL DO ESTADO',:sigla=>'AUDI',:entidade_id=>e.id)
Orgao.create(:codigo=>'23',:nome=>'CORPO DE BOMBEIROS MILITAR',:sigla=>'CBM',:entidade_id=>e.id)
Orgao.create(:codigo=>'19',:nome=>'DEFENSORIA PUBLICA DO ESTADO',:sigla=>'DEFENAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'24',:nome=>'DEPART. DE POLICIA TEC CIENTIFICA',:sigla=>'POLITEC',:entidade_id=>e.id)
Orgao.create(:codigo=>'32',:nome=>'DEPARTAMENTO ESTADUAL DE TRANSITO',:sigla=>'DETRAN',:entidade_id=>e.id)
Orgao.create(:codigo=>'31',:nome=>'ESCOLA DE ADM. PÚBLICA DO AMAPÁ',:sigla=>'EAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'38',:nome=>'FUNDACAO DA CRIANCA E DO ADOLESCENT',:sigla=>'FCRIA',:entidade_id=>e.id)
Orgao.create(:codigo=>'01',:nome=>'GABINETE CIVIL DO GOVERNADOR',:sigla=>'GABI',:entidade_id=>e.id)
Orgao.create(:codigo=>'41',:nome=>'INSTITUTO DE ADMINISTRAÇÃO PENITENC',:sigla=>'IAPEN',:entidade_id=>e.id)
Orgao.create(:codigo=>'37',:nome=>'INSTITUTO DE DESEN. RURAL DO AMAPA',:sigla=>'RURAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'28',:nome=>'INSTITUTO DE HEMOT. E HEMATOLOGIA',:sigla=>'HEMOAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'36',:nome=>'INSTITUTO DE MEIO AMB. E ORD. TERR.',:sigla=>'IMAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'42',:nome=>'INSTITUTO DE PESCA DO AMAPÁ',:sigla=>'PESCAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'44',:nome=>'INSTITUTO DE PESO E MED. DO AMAPA',:sigla=>'IPEM',:entidade_id=>e.id)
Orgao.create(:codigo=>'26',:nome=>'INSTITUTO DE PESQUISA DO AMAPA',:sigla=>'IEPA',:entidade_id=>e.id)
Orgao.create(:codigo=>'54',:nome=>'INSTITUTO EST. FLORESTA DO AMAPÁ',:sigla=>'IEFAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'39',:nome=>'JUNTA COMERCIAL DO ESTADO DO AMAPA',:sigla=>'JUCAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'27',:nome=>'LABORATORIO CENTRAL DO ESTADO',:sigla=>'LACEN',:entidade_id=>e.id)
Orgao.create(:codigo=>'49',:nome=>'OUVIDORIA GERAL DO ESTADO',:sigla=>'OGEAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'12',:nome=>'POLICIA MILITAR DO ESTADO',:sigla=>'PMAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'22',:nome=>'PROCESSAMENTO DE DADOS DO AMAPA',:sigla=>'PRODAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'50',:nome=>'PROCOM',:sigla=>'PROCOM',:entidade_id=>e.id)
Orgao.create(:codigo=>'17',:nome=>'PROCURADORIA GERAL DO ESTADO',:sigla=>'PROG',:entidade_id=>e.id)
Orgao.create(:codigo=>'34',:nome=>'RADIO DIFUSORA DE MACAPA',:sigla=>'RDM',:entidade_id=>e.id)
Orgao.create(:codigo=>'02',:nome=>'REPRESENTACAO GEA BELEM',:sigla=>'REPBELEM',:entidade_id=>e.id)
Orgao.create(:codigo=>'03',:nome=>'REPRESENTACAO GEA BRASILIA',:sigla=>'REPBSB',:entidade_id=>e.id)
Orgao.create(:codigo=>'59',:nome=>'SEC EXTRA DE POL AFRO-DESCENDENTES',:sigla=>'SEPAFRO',:entidade_id=>e.id)
Orgao.create(:codigo=>'57',:nome=>'SEC EXTRAOR DE POL PARA A JUVENTUDE',:sigla=>'SEPJUV',:entidade_id=>e.id)
Orgao.create(:codigo=>'58',:nome=>'SEC EXTRAOR DE POLITI PARA MULHERES',:sigla=>'SEPMUL',:entidade_id=>e.id)
Orgao.create(:codigo=>'56',:nome=>'SEC EXTRAORD DOS POVOS INDIGENAS',:sigla=>'SEPIND',:entidade_id=>e.id)
Orgao.create(:codigo=>'09',:nome=>'SEC. DA AGRIC. PESCA FLOR. E ABAST.',:sigla=>'SEAF',:entidade_id=>e.id)
Orgao.create(:codigo=>'07',:nome=>'SEC. DE EST. DA INFRA-ESTRUTURA',:sigla=>'SEINF',:entidade_id=>e.id)
Orgao.create(:codigo=>'06',:nome=>'SEC. DE EST. DA JUST E SEG PUBLICA',:sigla=>'SEJUSP',:entidade_id=>e.id)
Orgao.create(:codigo=>'18',:nome=>'SEC. DE EST. DO MEIO-AMBIENTE',:sigla=>'SEMA',:entidade_id=>e.id)
Orgao.create(:codigo=>'11',:nome=>'SEC. DE EST. DO PLAN. OR. E TESOURO',:sigla=>'SEPLAN',:entidade_id=>e.id)
Orgao.create(:codigo=>'16',:nome=>'SEC. DE EST. DO TRAB. E EMPREEND.',:sigla=>'SETE',:entidade_id=>e.id)
Orgao.create(:codigo=>'25',:nome=>'SECRET. DE EST. DO DESPORTO E LAZER',:sigla=>'SEDEL',:entidade_id=>e.id)
Orgao.create(:codigo=>'21',:nome=>'SECRET. IND. COM. E MINERACAO',:sigla=>'SEICOM',:entidade_id=>e.id)
Orgao.create(:codigo=>'05',:nome=>'SECRETARIA DA RECEITA ESTADUAL',:sigla=>'SERES',:entidade_id=>e.id)
Orgao.create(:codigo=>'43',:nome=>'SECRETARIA DE E. TECNOLOGIA',:sigla=>'SETEC',:entidade_id=>e.id)
Orgao.create(:codigo=>'30',:nome=>'SECRETARIA DE EST. CULTURA DO AMAPÁ',:sigla=>'SECULT',:entidade_id=>e.id)
Orgao.create(:codigo=>'14',:nome=>'SECRETARIA DE EST. DA ADMINISTRACAO',:sigla=>'SEAD',:entidade_id=>e.id)
Orgao.create(:codigo=>'10',:nome=>'SECRETARIA DE EST. DA EDUCACAO',:sigla=>'SEED',:entidade_id=>e.id)
Orgao.create(:codigo=>'20',:nome=>'SECRETARIA DE ESTADO DA COMUNICACAO',:sigla=>'SECOM',:entidade_id=>e.id)
Orgao.create(:codigo=>'08',:nome=>'SECRETARIA DE ESTADO DA SAUDE',:sigla=>'SESA',:entidade_id=>e.id)
Orgao.create(:codigo=>'29',:nome=>'SECRETARIA DE ESTADO DO TURISMO',:sigla=>'SETUR',:entidade_id=>e.id)
Orgao.create(:codigo=>'48',:nome=>'SECRETARIA ESPECIAL DE GOVERNO',:sigla=>'SEGOV',:entidade_id=>e.id)
Orgao.create(:codigo=>'40',:nome=>'SECRETARIA EST. INC. E MOB. SOCIAL',:sigla=>'SEIMS',:entidade_id=>e.id)
Orgao.create(:codigo=>'33',:nome=>'SECRETARIA ESTADUAL DE TRANSPORTE',:sigla=>'SETRAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'53',:nome=>'SECRETARIAS ESPECIAIS',:sigla=>'SEESP',:entidade_id=>e.id)
Orgao.create(:codigo=>'47',:nome=>'SIAC - SUPER FÁCIL',:sigla=>'SIAC',:entidade_id=>e.id)
Orgao.create(:codigo=>'46',:nome=>'UNIVERSIDADE DO ESTADO DO AMAPÁ',:sigla=>'UEAP',:entidade_id=>e.id)
Orgao.create(:codigo=>'04',:nome=>'VICE-GOVERNADORIA DO ESTADO',:sigla=>'VICEGOV',:entidade_id=>e.id)
Cargo.all.each do |c|
     c.entidade_id=e.id
     c.save
 end
