# -*- encoding : utf-8 -*-
class UpdateContratos2 < ActiveRecord::Migration
  def self.up
  	User.usuario_atual = User.find 1
  	f595 = Funcionario.find_by_matricula('1064320')
f737 = Funcionario.find_by_matricula('1058738')
f1012 = Funcionario.find_by_matricula('1051113')
f673 = Funcionario.find_by_matricula('1051245')
f103 = Funcionario.find_by_matricula('1069098')
f448 = Funcionario.find_by_matricula('1053477')
f817 = Funcionario.find_by_matricula('1056859')
f352 = Funcionario.find_by_matricula('1055801')
f153 = Funcionario.find_by_matricula('1064436')
f524 = Funcionario.find_by_matricula('1067028')
f1036 = Funcionario.find_by_matricula('1051202')
f572 = Funcionario.find_by_matricula('1052764')
f705 = Funcionario.find_by_matricula('1065246')
f2 = Funcionario.find_by_matricula('528927')
f247 = Funcionario.find_by_matricula('1064134')
f633 = Funcionario.find_by_matricula('919985')
f660 = Funcionario.find_by_matricula('665894')
f498 = Funcionario.find_by_matricula('1056913')
f1008 = Funcionario.find_by_matricula('561304')
f534 = Funcionario.find_by_matricula('1063901')
f376 = Funcionario.find_by_matricula('664154')
f313 = Funcionario.find_by_matricula('991570')
f370 = Funcionario.find_by_matricula('900249')
f115 = Funcionario.find_by_matricula('1057995')
f483 = Funcionario.find_by_matricula('958360')
f441 = Funcionario.find_by_matricula('1064363')
f48 = Funcionario.find_by_matricula('671487')
f223 = Funcionario.find_by_matricula('1053485')
f552 = Funcionario.find_by_matricula('1063871')
f1047 = Funcionario.find_by_matricula('1064002')
f812 = Funcionario.find_by_matricula('1041371')
f1055 = Funcionario.find_by_matricula('946737')
f569 = Funcionario.find_by_matricula('970859')
f616 = Funcionario.find_by_matricula('654116')
f844 = Funcionario.find_by_matricula('687723')
f838 = Funcionario.find_by_matricula('1065408')
f894 = Funcionario.find_by_matricula('1067532')
f257 = Funcionario.find_by_matricula('1052241')
f135 = Funcionario.find_by_matricula('1055720')
f406 = Funcionario.find_by_matricula('1059130')
f687 = Funcionario.find_by_matricula('1069110')
f1058 = Funcionario.find_by_matricula('1064240')
f129 = Funcionario.find_by_matricula('1066811')
f447 = Funcionario.find_by_matricula('657336')
f80 = Funcionario.find_by_matricula('1052055')
f815 = Funcionario.find_by_matricula('692760')
f1046 = Funcionario.find_by_matricula('988308')
f543 = Funcionario.find_by_matricula('984264')
f674 = Funcionario.find_by_matricula('603384')
f213 = Funcionario.find_by_matricula('943673')
f243 = Funcionario.find_by_matricula('1041495')
f1028 = Funcionario.find_by_matricula('1052780')
f260 = Funcionario.find_by_matricula('1062611')
f94 = Funcionario.find_by_matricula('1051318')
f813 = Funcionario.find_by_matricula('1025856')
f31 = Funcionario.find_by_matricula('988073')
f618 = Funcionario.find_by_matricula('285900')
f455 = Funcionario.find_by_matricula('1051237')
f127 = Funcionario.find_by_matricula('1067427')
f1038 = Funcionario.find_by_matricula('1059106')
f528 = Funcionario.find_by_matricula('649627')
f707 = Funcionario.find_by_matricula('1052853')
f1052 = Funcionario.find_by_matricula('649368')
f66 = Funcionario.find_by_matricula('1018914')
f734 = Funcionario.find_by_matricula('985716')
f766 = Funcionario.find_by_matricula('695882')
f601 = Funcionario.find_by_matricula('654531')
f185 = Funcionario.find_by_matricula('688290')
f711 = Funcionario.find_by_matricula('1052012')
f291 = Funcionario.find_by_matricula('1064215')
f466 = Funcionario.find_by_matricula('1053450')
f675 = Funcionario.find_by_matricula('900060')
f240 = Funcionario.find_by_matricula('652172')
f237 = Funcionario.find_by_matricula('1052772')
f962 = Funcionario.find_by_matricula('1001957')
f112 = Funcionario.find_by_matricula('1053329')
f1096 = Funcionario.find_by_matricula('882070')
f353 = Funcionario.find_by_matricula('1000390')
f865 = Funcionario.find_by_matricula('1062069')
f801 = Funcionario.find_by_matricula('1061747')
f870 = Funcionario.find_by_matricula('1061747')
f594 = Funcionario.find_by_matricula('1064290')
f161 = Funcionario.find_by_matricula('1064169')
f429 = Funcionario.find_by_matricula('1052098')
f922 = Funcionario.find_by_matricula('935581')
f822 = Funcionario.find_by_matricula('661422')
f132 = Funcionario.find_by_matricula('1056697')
f945 = Funcionario.find_by_matricula('670820')
f124 = Funcionario.find_by_matricula('1052225')
f155 = Funcionario.find_by_matricula('925098')
f741 = Funcionario.find_by_matricula('659320')
f150 = Funcionario.find_by_matricula('1056670')
f624 = Funcionario.find_by_matricula('1052233')
f128 = Funcionario.find_by_matricula('1051105')
f131 = Funcionario.find_by_matricula('1063995')
f1053 = Funcionario.find_by_matricula('1058363')
f663 = Funcionario.find_by_matricula('649180')
f533 = Funcionario.find_by_matricula('1064452')
f1066 = Funcionario.find_by_matricula('1058274')
f646 = Funcionario.find_by_matricula('1057952')
f636 = Funcionario.find_by_matricula('1056964')
f33 = Funcionario.find_by_matricula('1064401')
f123 = Funcionario.find_by_matricula('672025')
f1082 = Funcionario.find_by_matricula('1052160')
f254 = Funcionario.find_by_matricula('1067516')
f810 = Funcionario.find_by_matricula('1056921')
f318 = Funcionario.find_by_matricula('637530')
f965 = Funcionario.find_by_matricula('678139')
f696 = Funcionario.find_by_matricula('929751')
f459 = Funcionario.find_by_matricula('658073')
f415 = Funcionario.find_by_matricula('1064053')
f1030 = Funcionario.find_by_matricula('664928')
f392 = Funcionario.find_by_matricula('1003038')
f804 = Funcionario.find_by_matricula('946540')
f305 = Funcionario.find_by_matricula('1061240')
f963 = Funcionario.find_by_matricula('958646')
f263 = Funcionario.find_by_matricula('1052837')
f856 = Funcionario.find_by_matricula('989363')
f114 = Funcionario.find_by_matricula('652784')
f1057 = Funcionario.find_by_matricula('1064339')
f529 = Funcionario.find_by_matricula('1052187')
f972 = Funcionario.find_by_matricula('1063928')
f697 = Funcionario.find_by_matricula('1058495')
f1029 = Funcionario.find_by_matricula('1058290')
f604 = Funcionario.find_by_matricula('962988')
f134 = Funcionario.find_by_matricula('963038')
f327 = Funcionario.find_by_matricula('1056905')
f43 = Funcionario.find_by_matricula('1064010')
f88 = Funcionario.find_by_matricula('1063880')
f298 = Funcionario.find_by_matricula('843091')
f439 = Funcionario.find_by_matricula('1065602')
f651 = Funcionario.find_by_matricula('1051300')
f700 = Funcionario.find_by_matricula('1051091')
f233 = Funcionario.find_by_matricula('946818')
f116 = Funcionario.find_by_matricula('1066579')
f232 = Funcionario.find_by_matricula('1052136')
f862 = Funcionario.find_by_matricula('960560')
f126 = Funcionario.find_by_matricula('654213')
f1021 = Funcionario.find_by_matricula('1056867')
f67 = Funcionario.find_by_matricula('1052888')
f626 = Funcionario.find_by_matricula('1061658')
f565 = Funcionario.find_by_matricula('1051296')
f664 = Funcionario.find_by_matricula('964727')
f694 = Funcionario.find_by_matricula('1056948')
f311 = Funcionario.find_by_matricula('1061305')
f755 = Funcionario.find_by_matricula('989452')
f855 = Funcionario.find_by_matricula('946583')
f564 = Funcionario.find_by_matricula('1051261')
f244 = Funcionario.find_by_matricula('1052195')
f345 = Funcionario.find_by_matricula('1065572')
f76 = Funcionario.find_by_matricula('1001140')
f379 = Funcionario.find_by_matricula('1064428')
f767 = Funcionario.find_by_matricula('1067508')
f354 = Funcionario.find_by_matricula('1053302')
f171 = Funcionario.find_by_matricula('966010')
f218 = Funcionario.find_by_matricula('1052900')
f661 = Funcionario.find_by_matricula('900427')
f330 = Funcionario.find_by_matricula('1052144')
f1060 = Funcionario.find_by_matricula('1064100')
f628 = Funcionario.find_by_matricula('1053469')
f701 = Funcionario.find_by_matricula('1051180')
f1056 = Funcionario.find_by_matricula('1067524')
f1033 = Funcionario.find_by_matricula('1056891')
f226 = Funcionario.find_by_matricula('1052209')
f542 = Funcionario.find_by_matricula('957984')
f300 = Funcionario.find_by_matricula('1052020')
f1061 = Funcionario.find_by_matricula('960403')
f325 = Funcionario.find_by_matricula('1065645')
f81 = Funcionario.find_by_matricula('1052810')
f373 = Funcionario.find_by_matricula('1059114')
f971 = Funcionario.find_by_matricula('1051199')
f1010 = Funcionario.find_by_matricula('1056816')
f259 = Funcionario.find_by_matricula('1052047')
f98 = Funcionario.find_by_matricula('1056832')
f837 = Funcionario.find_by_matricula('1065360')
f877 = Funcionario.find_by_matricula('850390')
f329 = Funcionario.find_by_matricula('1065300')
f29 = Funcionario.find_by_matricula('1067044')
f944 = Funcionario.find_by_matricula('1064355')
f194 = Funcionario.find_by_matricula('920010')
f504 = Funcionario.find_by_matricula('1064029')
f539 = Funcionario.find_by_matricula('1056824')
f467 = Funcionario.find_by_matricula('660949')
f726 = Funcionario.find_by_matricula('1057936')
f547 = Funcionario.find_by_matricula('1052845')
f292 = Funcionario.find_by_matricula('1052250')
f266 = Funcionario.find_by_matricula('1066714')
f336 = Funcionario.find_by_matricula('1051172')
f1023 = Funcionario.find_by_matricula('1057944')
f462 = Funcionario.find_by_matricula('667129')
f691 = Funcionario.find_by_matricula('958670')
f304 = Funcionario.find_by_matricula('697699')
f83 = Funcionario.find_by_matricula('665045')
f211 = Funcionario.find_by_matricula('699675')
f214 = Funcionario.find_by_matricula('1065696')
f932 = Funcionario.find_by_matricula('1056751')
f87 = Funcionario.find_by_matricula('912743')
f256 = Funcionario.find_by_matricula('1064398')
f321 = Funcionario.find_by_matricula('911623')
f657 = Funcionario.find_by_matricula('1065351')
f1086 = Funcionario.find_by_matricula('654892')
f814 = Funcionario.find_by_matricula('1065599')
f614 = Funcionario.find_by_matricula('1064096')
f371 = Funcionario.find_by_matricula('1062034')
f830 = Funcionario.find_by_matricula('1051270')
f310 = Funcionario.find_by_matricula('1052063')
f113 = Funcionario.find_by_matricula('1065424')
f736 = Funcionario.find_by_matricula('876453')
f537 = Funcionario.find_by_matricula('1053493')
f258 = Funcionario.find_by_matricula('1052918')
f130 = Funcionario.find_by_matricula('1066820')
f287 = Funcionario.find_by_matricula('960241')
f561 = Funcionario.find_by_matricula('1056930')
f267 = Funcionario.find_by_matricula('1052926')
f1049 = Funcionario.find_by_matricula('1064045')
f229 = Funcionario.find_by_matricula('1052802')
f421 = Funcionario.find_by_matricula('1066676')
f993 = Funcionario.find_by_matricula('1059149')
f246 = Funcionario.find_by_matricula('1055712')
f280 = Funcionario.find_by_matricula('1058525')
f703 = Funcionario.find_by_matricula('1067010')
f293 = Funcionario.find_by_matricula('653390')
f479 = Funcionario.find_by_matricula('1064223')
f943 = Funcionario.find_by_matricula('1068954')
f340 = Funcionario.find_by_matricula('1064266')
f1075 = Funcionario.find_by_matricula('1066544')
f301 = Funcionario.find_by_matricula('1052799')
f349 = Funcionario.find_by_matricula('1052756')
f1039 = Funcionario.find_by_matricula('1058266')
f888 = Funcionario.find_by_matricula('850608')
f557 = Funcionario.find_by_matricula('987611')
f20 = Funcionario.find_by_matricula('1051326')
f109 = Funcionario.find_by_matricula('1063987')
f623 = Funcionario.find_by_matricula('946052')
f818 = Funcionario.find_by_matricula('1052748')
f659 = Funcionario.find_by_matricula('950530')
f559 = Funcionario.find_by_matricula('1064371')
f950 = Funcionario.find_by_matricula('1063960')
f269 = Funcionario.find_by_matricula('935670')
f668 = Funcionario.find_by_matricula('1056956')
f44 = Funcionario.find_by_matricula('1064940')
f684 = Funcionario.find_by_matricula('1051210')
f582 = Funcionario.find_by_matricula('979007')
f617 = Funcionario.find_by_matricula('1064410')
f839 = Funcionario.find_by_matricula('989274')
f686 = Funcionario.find_by_matricula('1051083')
f544 = Funcionario.find_by_matricula('1057960')
f834 = Funcionario.find_by_matricula('1058720')
f399 = Funcionario.find_by_matricula('1057782')
f1065 = Funcionario.find_by_matricula('1051288')
f739 = Funcionario.find_by_matricula('1058681')
f869 = Funcionario.find_by_matricula('1061712')
f489 = Funcionario.find_by_matricula('1064061')
f805 = Funcionario.find_by_matricula('946605')
f360 = Funcionario.find_by_matricula('1056689')
f842 = Funcionario.find_by_matricula('1065670')
f279 = Funcionario.find_by_matricula('1065718')
f251 = Funcionario.find_by_matricula('1064380')
f248 = Funcionario.find_by_matricula('1065610')
f302 = Funcionario.find_by_matricula('1052861')
f1088 = Funcionario.find_by_matricula('1069063')
f1087 = Funcionario.find_by_matricula('1065270')
f328 = Funcionario.find_by_matricula('1062042')
f1062 = Funcionario.find_by_matricula('1069101')
f885 = Funcionario.find_by_matricula('960349')
f823 = Funcionario.find_by_matricula('1056735')
f92 = Funcionario.find_by_matricula('1067060')
f743 = Funcionario.find_by_matricula('959758')
f639 = Funcionario.find_by_matricula('1064835')
f881 = Funcionario.find_by_matricula('1057812')
f265 = Funcionario.find_by_matricula('1064118')
f227 = Funcionario.find_by_matricula('1052217')
f332 = Funcionario.find_by_matricula('1064282')
f1077 = Funcionario.find_by_matricula('1056972')
f416 = Funcionario.find_by_matricula('1065840')
f540 = Funcionario.find_by_matricula('978329')
f166 = Funcionario.find_by_matricula('1066951')
f1051 = Funcionario.find_by_matricula('1064088')
f430 = Funcionario.find_by_matricula('910635')
f339 = Funcionario.find_by_matricula('1051164')
f383 = Funcionario.find_by_matricula('960144')
f1089 = Funcionario.find_by_matricula('1058029')
f389 = Funcionario.find_by_matricula('1066501')
f319 = Funcionario.find_by_matricula('1056743')
f654 = Funcionario.find_by_matricula('977462')
f1022 = Funcionario.find_by_matricula('1057251')
f409 = Funcionario.find_by_matricula('987050')
f290 = Funcionario.find_by_matricula('1052039')
f361 = Funcionario.find_by_matricula('1065416')
f238 = Funcionario.find_by_matricula('1052896')
f217 = Funcionario.find_by_matricula('1052829')
f487 = Funcionario.find_by_matricula('1064924')
f1011 = Funcionario.find_by_matricula('843261')
f395 = Funcionario.find_by_matricula('1065637')
f996 = Funcionario.find_by_matricula('1057774')
f912 = Funcionario.find_by_matricula('1066854')
f656 = Funcionario.find_by_matricula('1068946')
f677 = Funcionario.find_by_matricula('1065874')
f723 = Funcionario.find_by_matricula('1057790')
f558 = Funcionario.find_by_matricula('943266')
f761 = Funcionario.find_by_matricula('1064347')
f772 = Funcionario.find_by_matricula('1063944')
f1071 = Funcionario.find_by_matricula('1058509')
f530 = Funcionario.find_by_matricula('1064150')
f198 = Funcionario.find_by_matricula('1057901')
f241 = Funcionario.find_by_matricula('1052179')
f369 = Funcionario.find_by_matricula('1052870')
f990 = Funcionario.find_by_matricula('1056980')
if f595 then f595.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f737 then f737.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f1012 then f1012.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f673 then f673.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f103 then f103.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f448 then f448.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f817 then f817.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f352 then f352.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f153 then f153.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f524 then f524.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f1036 then f1036.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f572 then f572.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f705 then f705.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f2 then f2.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f247 then f247.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f633 then f633.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f660 then f660.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f498 then f498.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f1008 then f1008.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f534 then f534.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f376 then f376.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Sociologia')) end
if f313 then f313.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f370 then f370.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f115 then f115.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f483 then f483.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f441 then f441.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f48 then f48.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f223 then f223.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ensino Religioso')) end
if f552 then f552.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f1047 then f1047.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f812 then f812.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1055 then f1055.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f569 then f569.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f616 then f616.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f844 then f844.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f838 then f838.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f894 then f894.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f257 then f257.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f135 then f135.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f406 then f406.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f687 then f687.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f1058 then f1058.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f129 then f129.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f447 then f447.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f80 then f80.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f815 then f815.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1046 then f1046.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f543 then f543.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f674 then f674.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f213 then f213.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f243 then f243.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f1028 then f1028.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f260 then f260.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f94 then f94.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f813 then f813.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f31 then f31.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f618 then f618.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f455 then f455.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f127 then f127.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1038 then f1038.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f528 then f528.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f707 then f707.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Espanhol')) end
if f1052 then f1052.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f66 then f66.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f734 then f734.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f766 then f766.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f601 then f601.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f185 then f185.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f711 then f711.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f291 then f291.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f466 then f466.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f675 then f675.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f240 then f240.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f237 then f237.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f962 then f962.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f112 then f112.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1096 then f1096.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f353 then f353.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f865 then f865.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f801 then f801.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f870 then f870.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f594 then f594.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f161 then f161.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f429 then f429.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f922 then f922.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f822 then f822.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f132 then f132.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f945 then f945.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f124 then f124.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f155 then f155.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f741 then f741.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f150 then f150.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f624 then f624.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f128 then f128.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f131 then f131.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1053 then f1053.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f663 then f663.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f533 then f533.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1066 then f1066.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f646 then f646.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Sociologia')) end
if f636 then f636.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f33 then f33.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f123 then f123.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1082 then f1082.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f254 then f254.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f810 then f810.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Sociologia')) end
if f318 then f318.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f965 then f965.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f696 then f696.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f459 then f459.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f415 then f415.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f1030 then f1030.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f392 then f392.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f804 then f804.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f305 then f305.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f963 then f963.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f263 then f263.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f856 then f856.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f114 then f114.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1057 then f1057.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f529 then f529.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f972 then f972.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f697 then f697.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f1029 then f1029.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f604 then f604.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f134 then f134.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f327 then f327.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f43 then f43.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f88 then f88.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f298 then f298.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f439 then f439.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f651 then f651.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f700 then f700.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f233 then f233.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f116 then f116.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f232 then f232.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f862 then f862.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f126 then f126.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1021 then f1021.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f67 then f67.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f626 then f626.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f565 then f565.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f664 then f664.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f694 then f694.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f311 then f311.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f755 then f755.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f855 then f855.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f564 then f564.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f244 then f244.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f345 then f345.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f76 then f76.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f379 then f379.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f767 then f767.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f354 then f354.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f171 then f171.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Espanhol')) end
if f218 then f218.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f661 then f661.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f330 then f330.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1060 then f1060.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f628 then f628.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f701 then f701.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f1056 then f1056.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1033 then f1033.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f226 then f226.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f542 then f542.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f300 then f300.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1061 then f1061.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f325 then f325.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f81 then f81.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f373 then f373.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f971 then f971.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f1010 then f1010.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f259 then f259.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f98 then f98.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f837 then f837.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f877 then f877.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f329 then f329.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ensino Religioso')) end
if f29 then f29.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f944 then f944.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f194 then f194.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f504 then f504.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f539 then f539.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f467 then f467.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f726 then f726.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f547 then f547.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f292 then f292.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f266 then f266.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f336 then f336.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1023 then f1023.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f462 then f462.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f691 then f691.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f304 then f304.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f83 then f83.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f211 then f211.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f214 then f214.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f932 then f932.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f87 then f87.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f256 then f256.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f321 then f321.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f657 then f657.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f1086 then f1086.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f814 then f814.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f614 then f614.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f371 then f371.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f830 then f830.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f310 then f310.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f113 then f113.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f736 then f736.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f537 then f537.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f258 then f258.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f130 then f130.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f287 then f287.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f561 then f561.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f267 then f267.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1049 then f1049.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f229 then f229.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f421 then f421.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f993 then f993.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f246 then f246.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f280 then f280.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f703 then f703.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f293 then f293.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f479 then f479.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Física')) end
if f943 then f943.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f340 then f340.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f1075 then f1075.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f301 then f301.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f349 then f349.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1039 then f1039.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f888 then f888.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f557 then f557.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Espanhol')) end
if f20 then f20.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f109 then f109.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f623 then f623.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f818 then f818.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f659 then f659.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f559 then f559.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f950 then f950.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f269 then f269.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f668 then f668.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Sociologia')) end
if f44 then f44.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f684 then f684.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Espanhol')) end
if f582 then f582.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f617 then f617.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f839 then f839.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f686 then f686.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f544 then f544.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f834 then f834.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f399 then f399.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f1065 then f1065.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f739 then f739.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f869 then f869.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f489 then f489.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f805 then f805.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f360 then f360.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f842 then f842.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f279 then f279.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f251 then f251.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f248 then f248.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f302 then f302.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1088 then f1088.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1087 then f1087.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f328 then f328.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f1062 then f1062.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f885 then f885.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f823 then f823.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f92 then f92.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Francês')) end
if f743 then f743.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f639 then f639.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f881 then f881.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f265 then f265.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f227 then f227.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('História')) end
if f332 then f332.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f1077 then f1077.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Matemática')) end
if f416 then f416.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f540 then f540.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f166 then f166.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f1051 then f1051.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f430 then f430.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f339 then f339.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f383 then f383.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f1089 then f1089.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f389 then f389.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f319 then f319.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f654 then f654.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f1022 then f1022.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f409 then f409.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f290 then f290.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f361 then f361.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f238 then f238.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f217 then f217.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa')) end
if f487 then f487.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f1011 then f1011.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Portuguesa e Literatura')) end
if f395 then f395.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f996 then f996.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f912 then f912.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f656 then f656.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Biologia')) end
if f677 then f677.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f723 then f723.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Geografia')) end
if f558 then f558.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f761 then f761.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
if f772 then f772.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Química')) end
if f1071 then f1071.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Artes')) end
if f530 then f530.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f198 then f198.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Língua Estrangeira - Inglês')) end
if f241 then f241.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Ciências')) end
if f369 then f369.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('1ª à 4ª series')) end
if f990 then f990.update_attributes(:disciplina_contratacao=>DisciplinaContratacao.find_by_nome('Educação Física')) end
  end

  def self.down
  end
end

